[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "pydeform"
version = "0.5.2"
description = ""
readme = "README.md"
authors = [
    { name = "Simon Ekström" },
]
dependencies = [
    "numpy",
    "python-stk",
    "PyYAML",
]
